### ISSUE TITLE
Can you implement conditional fields and field-values with yafowil?

### ISSUE THREAD

**Issue by pbauer** [conestack/yafowil#35]
Does yafowil in any way help me to add/remove/modify existing fields or their options based on the selected values of other fields of the same form?

**Comment by rnixx** [comment]
if you want yafowil to help you directly with this you need to submit the form for every change you make since yafowil forms are computed server side. the other option is to deliver the available options and write some lines of JS for hiding/showing fields based on selected options.

**Comment by pbauer** [comment]
My question is now obsolete due to https://github.com/collective/collective.easyform/pull/352
